import { jsPDF } from "jspdf";
import { Intervention } from "./types";

export const generatePDF = (intv: Intervention) => {
  const doc = new jsPDF();
  doc.setFontSize(22);
  doc.setTextColor(30, 58, 138);
  doc.text("FICHE D'INTERVENTION", 105, 20, { align: "center" });
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Ticket N°: ${intv.ticketId}`, 20, 35);
  doc.text(`Date: ${new Date(intv.createdAt).toLocaleDateString()}`, 140, 35);
  doc.setDrawColor(200);
  doc.line(20, 40, 190, 40);
  doc.setFontSize(14);
  doc.setTextColor(30, 58, 138);
  doc.text("Informations Client", 20, 50);
  doc.setFontSize(10);
  doc.setTextColor(50);
  doc.text(`Nom: ${intv.client.prenom} ${intv.client.nom}`, 20, 60);
  if (intv.client.entreprise) doc.text(`Entreprise: ${intv.client.entreprise}`, 20, 65);
  doc.text(`Téléphone: ${intv.client.telephone} (WA: ${intv.client.whatsapp})`, 20, 70);
  doc.text(`Localisation: ${intv.client.ville}, ${intv.client.quartier} - ${intv.client.adresse}`, 20, 75);
  doc.setDrawColor(200);
  doc.line(20, 85, 190, 85);
  doc.setFontSize(14);
  doc.setTextColor(30, 58, 138);
  doc.text("Matériel", 20, 95);
  doc.setFontSize(10);
  doc.setTextColor(50);
  doc.text(`Type: ${intv.equipement.type}`, 20, 105);
  doc.text(`Marque: ${intv.equipement.marque} | Modèle: ${intv.equipement.modele}`, 20, 110);
  doc.text(`N° Série: ${intv.equipement.numero_serie}`, 20, 115);
  doc.line(20, 125, 190, 125);
  doc.setFontSize(14);
  doc.setTextColor(30, 58, 138);
  doc.text("Description du problème", 20, 135);
  doc.setFontSize(10);
  doc.setTextColor(50);
  doc.text(`Catégorie: ${intv.probleme.categorie} | Urgence: ${intv.probleme.urgence}`, 20, 145);
  const descLines = doc.splitTextToSize(`Description: ${intv.probleme.description}`, 170);
  doc.text(descLines, 20, 155);
  const offset1 = 155 + (descLines.length * 5);
  const symptLines = doc.splitTextToSize(`Symptômes: ${intv.probleme.symptomes}`, 170);
  doc.text(symptLines, 20, offset1);
  const offset2 = offset1 + (symptLines.length * 5);
  doc.line(20, offset2 + 5, 190, offset2 + 5);
  return doc;
};
